name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: spdx-ensure
        run: |
          ./tools/spdx-ensure
